server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # SPA routing: qualquer rota não encontrada retorna o index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Sem exposição de informações de versão do servidor
    server_tokens off;
}
