apiVersion: v1
kind: Namespace
metadata:
  name: vigilantia
  labels:
    app.kubernetes.io/name: vigilantia
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
